### ISSUE TITLE
Face Rect is not accurate in Lansdcape mode.

### ISSUE THREAD

**Issue by happysingh23828** [hongbeomi/MacGyver#1]
Face Rects is getting away in landscape mode.
![device-2020-11-26-140955](https://user-images.githubusercontent.com/26920113/100327291-2176f500-2ff1-11eb-8461-6ec88c97a711.png)

**Comment by hongbeomi** [comment]
Oh, thank you for bringing up the problem. I haven't actually tested it in landscape mode, but I'll try to solve it.

**Comment by happysingh23828** [comment]
Thanks, @hongbeomi  for the quick reply, waiting to get it fixed.  :+1:

**Comment by hongbeomi** [comment]
The issue has been resolved.😀 @happysingh23828

**Comment by happysingh23828** [comment]
let me check @hongbeomi , you are super crazy :100:

**Comment by hongbeomi** [comment]
Thank you👍

**Comment by happysingh23828** [comment]
Thanks, Bro, it's working :1st_place_medal: , closing this issue
