### ISSUE TITLE
a question

### ISSUE THREAD

**Issue by MR-GuoQing** [hongbeomi/MacGyver#2]
Why the 'scale' will use the larger ratio of 'scaleX' and 'scaleY' in barcode mode?
and i have tried using like this:  

val mappedBox1 = RectF().apply {
                left = boundingBoxT.right * scaleX
                top = boundingBoxT.top * scaleY 
                right = boundingBoxT.left * scaleX 
                bottom = boundingBoxT.bottom * scaleY 
            }
but seems not mach the barcode box very closely?  please correct me,  thanks

**Comment by hongbeomi** [comment]
@MR-GuoQing 
If you use the code you wrote, x coordinates will be out of order in portrait mode, and y coordinates will be out of order in landscape mode. because `scale` is to get the ratio of `Image` and `GraphicOverlay(match_parent)`. This is because the same ratio must be applied according to each mode to produce the correct coordinate value.

**Comment by MR-GuoQing** [comment]
Thanks for reply.  if i convert  `Image` to `Bitmap` and apply the code:
```java
val mappedBox1 = RectF().apply {
left = boundingBoxT.left * scaleX
top = boundingBoxT.top * scaleY
right = boundingBoxT.right * scaleX
bottom = boundingBoxT.bottom * scaleY
}  

```
the coordinate will be right in landscape mode but not try the front mode, please notice i did not opposite the `boundingBox.left` and `boundingBox.right`.  and i don't know why  barcode box rect is different between the `YUV` data and  `Bitmap` from detect client.

**Comment by hongbeomi** [comment]
@MR-GuoQing 
Well, I tested the original code and your code.

- First, the result of the original code. (I suggest you zoom in😅)

**portrait mode**
<img src="https://user-images.githubusercontent.com/40753104/100411112-1b961800-30b4-11eb-9e25-d04df7836547.jpeg" width="40%">

**landscape mode**
  <img src="https://user-images.githubusercontent.com/40753104/100411133-310b4200-30b4-11eb-8eb0-5a3db3244714.jpeg" width="40%"> 

---
- Second, the result of your code.

**portrait mode**
<img src="https://user-images.githubusercontent.com/40753104/100411284-a2e38b80-30b4-11eb-8734-904d7984f1bd.jpeg" width="40%">

**landscape mode**
<img src="https://user-images.githubusercontent.com/40753104/100411308-b5f65b80-30b4-11eb-952b-f38a51500353.jpeg" width="40%">

The above results look similar, but there is a difference in coordinates of x in portrait mode and y in landscape mode.

I don't know what YUV value means.😞

**Comment by MR-GuoQing** [comment]
Thanks,  i have understood. the landscape mode width is

**Comment by MR-GuoQing** [comment]
If we only consider portrait mode, can you give me more detail about you calculate?  very appreciate that.  
I have a demo using my code, another different is i am using the `InputImage.fromBitmap(bitmap, 0)`  i transform the 'Image' to 'Bitmap' and rotate 90 in portrait mode. and the `YUV` is the image raw data format using in camerax and camera2. we can get the `YUV` data from `image.planes`. `Y` -`planes[0]`, `U` -`planes[1]`, `V`-`planes[2]`. So i was confusing the boundbox rect is different from `InputImage.fromBitmap(bitmap, 0)` and `InputImage.fromMediaImage(image, imageProxy.imageInfo.rotationDegrees)`
the screenshot as bellow
![Screenshot_20201127-001856](https://user-images.githubusercontent.com/22808151/100421045-8fd7b800-30c2-11eb-9410-e9f9d938c7a4.png)

**Comment by hongbeomi** [comment]
I think it would be good to look [here](https://developers.google.com/android/reference/com/google/mlkit/vision/common/InputImage#fromMediaImage(android.media.Image,%20int)) for the `InputImage` section. 

If you look at the `calculatorRect` function of the `GraphicOverlay` class, assuming only portrait mode is used, you should first calculate the magnification ratio of the width and height of the image, and calculate the offset of x and y respectively. For offset, subtract the magnification ratio of the image from the width and height of the current overlay view and divide by 2. Then, multiply the coordinates by the width and height, and then add the offset. If you are in selfie mode, you can get the center coordinates and reverse them.

**Comment by MR-GuoQing** [comment]
Thanks, I understand  calculatorRect function, but confusing on some point.
```java
    val scaleX = overlay.width.toFloat() / whenLandScapeModeWidth()
    val scaleY = overlay.height.toFloat() / whenLandScapeModeHeight()
// why scale using the larger one (is that mean we should keep the same magnification ratio in image's width and height. 
//then calculate the offset of rest  )?  for example, if scale equals scaleY, that means  `overlay.width.toFloat() < whenLandScapeModeWidth()*scale `
// and  `overlay.height.toFloat() = whenLandScapeModeHeight()*scale `, so offsetY =0 and offsetX < 0.
//from the result of your app, is it the rule that PreviewView to show the camera stream? (Keep the largest magnification ratio from x and y, then calculate the rest by offset?)
    val scale = scaleX.coerceAtLeast(scaleY)
    overlay.mScale = scale
```

**Comment by MR-GuoQing** [comment]
I have understood now, my code work only when preview aspect ratio(16:9 or 4:3) is same as image.

**Comment by hongbeomi** [comment]
LGTM
