### ISSUE TITLE
Take and save photo while live rendering face recognition.

### ISSUE THREAD

**Issue by DraganMaricDeveloper** [hongbeomi/MacGyver#3]
Hi there. I have a suggestion: Is it possible to save(capture) photo while camera is live rendering face detection. So, not to save photo and later decorate bitmap and save, but to capture photo while camera is detecting faces and it draws on canvas as on your example, color dots on eye, mouth etc. And save that as a last image all together(what user sees on a screen). 

Cheers.

**Comment by hongbeomi** [comment]
Thank you for raising the issue.

**Comment by hongbeomi** [comment]
@DraganMaricDeveloper 

https://github.com/hongbeomi/MacGyver/commit/e8b84cbb834c56b5f877fe9c66e21cb046301ee8

I've added the ability to take pictures. Check it out here 😀

**Comment by DraganMaricDeveloper** [comment]
Hi. I have checked and it works great :) Nice job! 

Suggestion: In BaseImageAnalyzer class -> 

```
    @SuppressLint("UnsafeExperimentalUsageError")
    override fun analyze(imageProxy: ImageProxy) {
        val mediaImage = imageProxy.image
        mediaImage?.let {
            detectInImage(InputImage.fromMediaImage(it, imageProxy.imageInfo.rotationDegrees))
                .addOnSuccessListener { results ->
                    onSuccess(
                        results,
                        graphicOverlay,
                        it.cropRect
                    )
                }
                .addOnFailureListener {
                graphicOverlay.clear()
                graphicOverlay.postInvalidate()
                    onFailure(it)
                }
                .addOnCompleteListener {
                    imageProxy.close()
                }
        }
    }
```
onFailureListener, I would add:
  graphicOverlay.clear()
                graphicOverlay.postInvalidate(). 
Or it is irrelevant? Do you know how to control image(Bitmap) quality export? Scaling, HDR ,ration etc?

**Comment by hongbeomi** [comment]
Oh, I think that's a good idea👍
I'm not sure about image-related processing.
