### ISSUE TITLE
Barcode overlay does not scale correctly with preview

### ISSUE THREAD

**Issue by leevigraham** [hongbeomi/MacGyver#5]
I've been struggling with this in my own project.

In this project the barcode overlay does not correctly scale with the preview.

I think this has something to do with the `imageProxy.cropRectangle`, `mediaImage.cropRectangle`, aspectRatio etc but I'm not sure.

![IMG_4192](https://user-images.githubusercontent.com/25124/124425718-4bc13a00-ddac-11eb-8db4-067ef17cbd68.JPG)

**Comment by hongbeomi** [comment]
I'll check. I have a lot of work on weekdays, so I'll check it around the weekend 😥

**Comment by leevigraham** [comment]
@hongbeomi No rush… I figured it out in my project, I'll try and simplify the logic and submit a PR.
